//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        public Place()
        {
            this.Route = new HashSet<Route>();
        }
    
        public int ID { get; set; }
        public int fk_City { get; set; }
        public System.Data.Entity.Spatial.DbGeography longitude { get; set; }
        public System.Data.Entity.Spatial.DbGeography latitude { get; set; }
        public string typeOfPlace { get; set; }
        public string dscrb { get; set; }
        public byte[] picture { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<Route> Route { get; set; }
    }
}
