//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        public Place()
        {
            this.RoutePoint = new HashSet<RoutePoint>();
        }
    
        public int ID { get; set; }
        public int fk_City { get; set; }
        public int typeOfPlace { get; set; }
        public string dscrb { get; set; }
        public byte[] picture { get; set; }
        public double longitude { get; set; }
        public double latitude { get; set; }
        public string name { get; set; }
        public string adress { get; set; }
    
        public virtual City City { get; set; }
        public virtual TypeOfPlace TypeOfPlace1 { get; set; }
        public virtual ICollection<RoutePoint> RoutePoint { get; set; }
    }
}
