//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoutePoint
    {
        public int IdRoutePoint { get; set; }
        public int IdPlace { get; set; }
        public int IdRoute { get; set; }
        public Nullable<int> PositionInRoute { get; set; }
    
        public virtual Place Place { get; set; }
        public virtual Route Route { get; set; }
    }
}
